### ISSUE TITLE
Load has_many associations under links

### ISSUE THREAD

**Issue by sahal2080** [gaorlov/deserializer#3]
Just like proposed in this draft library:
https://github.com/kurko/active_model_deserializers

**Comment by gaorlov** [comment]
I intentionally left out has_many to discourage people from passing in nested attributes into write endpoints, but if there's demand for it, i can easily add them.

**Comment by sahal2080** [comment]
I think that was also the goal of the library that I mentioned as it loads associations only as links. Please take a look through it whenever you have time and let me know what you think.

**Comment by gaorlov** [comment]
I looked at it, but i'm not entirely sure what the use case is. Can you tell me more a little bit about what you're trying to do? Are you using the deserializer as the client-side parsing library?

**Comment by sahal2080** [comment]
Not really as I'm using it to parse for the server itself. However, the client (Android app in my case) sends deeply nested data which I have no control over.

**Comment by gaorlov** [comment]
Oh ok. That makes sense. So do you want it to be the links, or would you be ok with just an array nested in the Json? Come to think of it, that's probably what that looks like anyway. I can probably whip something up for you.

**Comment by gaorlov** [comment]
I'm having a hard time finding a spec for the linked data. can you give me an example blob of JSON to work with? As of right now i'm going to build nested has_many association, like
```json
{ "id":6,
  "body":"this is a post",
  "comments" : [
    { "id":15,
       "body" : "first lol",
       "user_id" : 38
    },
    { "id": 22,
      "body" : "whatever",
      "user_id" : 63
    }
  ],
  "user_id": 40
}
```
will become
```ruby
{id: 6,
 body: "this is a post",
 comments: [
  {id: 15,
    body: ...},
  #... etc
]}

**Comment by gaorlov** [comment]
Take a look at the docs in the [has_many](https://github.com/gaorlov/deserializer/tree/has_many) branch and let me know if that works for you. You can build the gem by
```bash
$ git pull
$ git checkout has_many
$ gem build deserializer.gemspec
$ mv deserializer-0.5.0.gem /my/app/vendor/cache
$ cd my/project
$ bundle install
etc
```

**Comment by gaorlov** [comment]
@sahal2080 bump. Does this solve your issue?

**Comment by sahal2080** [comment]
So sorry for not responding sooner as I've been drowning in year end projects! I'll give it a proper testing by this Wednesday.

**Comment by gaorlov** [comment]
No worries. Just wanted to make sure that you saw the changes

**Comment by sahal2080** [comment]
Sorry for the delay but didn't have something to test with till today.
I'm actually getting this exception:
```
ActiveRecord::AssociationTypeMismatch - LineItem(#57572400) expected, got Hash(#16942360):
```
The incoming json:
```json
{
  "line_items": [
    {
      "modifiers": [
        {
          "modifier_uuid": "00052816-6a46-5cc8-c0be-f1dc28c65500",
          "modifier_id": 0
        }
      ],
      "line_item_uuid": "00052816-6905-8fc8-c0be-f1dc28c65500",
      "line_item_id": 0
    }
  ],
  "order_uuid": "00052816-60b7-d060-c0be-f1dc28c65500",
  "order_id": 0
}
```
The models:
- `Order` has_many line items
- `LineItem` has_many modifiers
- `Modifier`

If you need any other data just let me know. Thanks!

**Comment by gaorlov** [comment]
Hm. Can i see the deserializer and the models? 
My guess is that you forgot to either
1. in `Order` define `accepts_nested_attributes_for :line_items`
2. in `LineItem` define `accepts_nested_attribute_for :modifiers`
3. in the Deserializer, the hash that needs to be outputted *has* to be something like
```ruby
{
  line_items_attributes: [
    { line_item_uuid: "00052816-6905-8fc8-c0be-f1dc28c65500",
      line_item_id: 0 # should this be just `id` since you're feeding this into LineItem?
      modifiers_attributes: [
        { modifier_uuid: "00052816-60b7-d060-c0be-f1dc28c65500",
          modifier_id: 0
        }
      ]
    }
  ]
  order_uuid: "00052816-60b7-d060-c0be-f1dc28c65500",
  order_id: 0
}
```
which would make your deserializers look something like
```ruby
class OrderDeserializer < Deserializer::Base
  attribute :uuid, key: order_uuid # I'm assuming you want Order.id, not Order.order_id here
  attribute :id,     key:order_id
  # has_many needs a key option. see interim solution below
  has_many :line_items, deserializer: LineItemDeserializer
end

class LineItemDeserializer < Deserializer::Base
  attribute :uuid, key: :line_item_uuid
  attribute :id,     key: :line_item_id

  has_many :modifiers, deserializer: ModifierDeserialzer
end

# etc
```
Where, because `has_many` does not currently have a `key` option you will have to manually do 
```ruby
class OrdersController < ApplicationController
  def update_or_whatever
    order_attrs = OrderDeserializer.from_params params
    # this is something i'll need to fix by adding the :key option to associations
    order_attrs[:line_items_attributes] = order_attrs[:line_items]
    
    order_attrs[:line_items_attributes].each do |line_item|
      line_item[:modifiers_attributes] = line_items[:modifiers]
    end

    @order = Order.new(order_attrs)
    respond_with @order # or whatever
  end
end
```
Let me know if that helps.

**Comment by sahal2080** [comment]
Thanks for the quick response. I tried all what you suggested but I'm still getting the same error :(

As I was debugging a couple of other scenarios are coming up and I would appreciate your answers/thoughts:
- For `has_many`, if a single record was sent, can Deserializer safely parse it if it came in either
array or single element form?
- Can Deserializer safely ignore associations if a request didn't include them because they were empty?
- Is there a way to access "parent" attributes (such as its `id`) within its child's
 deserializer? I'm thinking of something like using `parent` for immediate parent, just like
 `object` is used for the model itself

**Comment by gaorlov** [comment]
I would need to see some code in order to give you a better answer. Can you show me how you use the desrializers in the models?

To answer your questions
* it expects an array
* it ignores fields that come in blank, so if you have a ton of stuff defined but get `{}` nothing should break
* there is not. All the deserializer does is hash manipulation. It doesn't have any understanding of association trees.

**Comment by sahal2080** [comment]
It almost certainly because of the association name issue. When I use your code (from above) in my controller but with `@order = Order.new(order_attrs.tap { |hs| hs.delete(:line_items) })`, it works. Hopefully when you're able to add the `:key` option to  associations it'll be fixed

**Comment by gaorlov** [comment]
`key:` support is added to `has_many`. Enjoy!

**Comment by gaorlov** [comment]
I merged everything into master and pushed into rubygems. Please use version 0.6.0
